### ISSUE TITLE
Preservation of `err.name` via `Boom.create` or `Boom[someMethod]`

### ISSUE THREAD

**Issue by niftylettuce** [hapijs/boom#138]
Shouldn't we be preserving the original `err.name`?

**Comment by niftylettuce** [comment]
Perhaps maybe detect if `message` is an `err` when passed to `internals.create` and if it is then wrap it instead?  Would be really nice to have this so we could use `Boom.badRequest(err)`. <https://github.com/hapijs/boom/blob/254593fd1d09e79049692675a4f9b7b5108b36d8/lib/index.js#L28>

**Comment by niftylettuce** [comment]
Currently the only way to do this is:

```js
{ ValidationError: Path is required
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  name: 'ValidationError',
  isBoom: true,
  isServer: false,
  data: null,
  output:
   { statusCode: 400,
     payload:
      { statusCode: 400,
        error: 'Bad Request',
        message: 'Path is required' },
     headers: {} },
  reformat: [Function] }
> Boom.wrap(err, 400).name
'ValidationError'
```

**Comment by niftylettuce** [comment]
See my pull request #139

**Comment by niftylettuce** [comment]
For anyone wondering why we need this and #139, the reason is to preserve error messages if you want to shorthand a method instead of having to remember status code.  For example, if there's a validation error in Mongoose, you can simply `ctx.throw(Boom.badRequest(err))` and if you also were to happen to use this <https://github.com/niftylettuce/koa-better-error-handler> as your error handler with Koa, then it will preserve the `err.name` for us to recognize the error as a ValidationError.  Otherwise there's not really a clean way to do this.  This is a minimal addition to `boom` that is fully tested and only adds two lines of code to the codebase.  I have added tests to #139 as well to keep 100% coverage.
