### ISSUE TITLE
Boom ignores Error message during wrap if statusCode is 500

### ISSUE THREAD

**Issue by cappslock** [hapijs/boom#159]
I'm unable to get Boom to create errors using the error.message when the status code is set to 500. I believe this is a bug as it conflicts with this bit from the docs:

> message - the error message derived from error.message

Examples:
```
Boom.wrap(new Error('test'))
--or--
Boom.wrap(new Error('test'), 500)

{ Error: test
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
--->    message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }

Expected message to be "test"
```

```
Boom.wrap(new Error('test'), 501)

{ Error: test
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 501,
---> payload: { statusCode: 501, error: 'Not Implemented', message: 'test' },
     headers: {} },
  reformat: [Function] }

Correctly sets message.
```

Haven't dug into the code, but I'm happy to take a crack at a PR if you agree this is a bug.

Boom 5.1.0, node 6.9.1

**Comment by hueniverse** [comment]
Read the manual.

https://github.com/hapijs/boom/blob/master/README.md#http-5xx-errors

**Comment by cappslock** [comment]
Yep, my bad.
