### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by julianheissl** [hapijs/boom#191]
Hi,

Boom npm package gets installed on my local machine OSx perfectly. But when i try to install it on my server with AWS EC2 instance, it gives following error:

node_modules/boom/lib/index.js:80
    constructor(message, options = {}) {
                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Project1-Services/utilities/error-codes/error-handling-util.js:1:76)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Project1-Services/routes/share-feed-handler/list-feeds.js:8:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Project1-Services/app.js:68:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

I tried reinstalling it again but nothing works. I'm stuck here. Please help me resolve this issue

**Comment by hueniverse** [comment]
Check your node versions.
