### ISSUE TITLE
new boom vs boomify docs misleading

### ISSUE THREAD

**Issue by kswope** [hapijs/boom#200]
From the docs

> new Boom(message, [options])
> message - the error message. **If message is an error, it is the same as calling boomify() directly**.

So I'm expecting the same output from both, but the constructor version doesn't remove the stack trace or the message

```
   import * as Boom from "boom"

    try {
      throw Error("hi")
    } catch (e) {
      console.log(JSON.stringify(new Boom(e), null, 4))
      console.log()
      console.log(JSON.stringify(Boom.boomify(e), null, 4))
    }
```

```
{
    "stack": "Error: hi\n    at Object.<anonymous> (/Users/kevin/Development/boom-demo/boom-test.ts:4:9)\n    at Module._compile (internal/modules/cjs/loader.js:654:30)\n    at Module.m._compile (/Users/kevin/Development/boom-demo/node_modules/ts-node/src/index.ts:403:23)\n    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)\n    at Object.require.extensions.(anonymous function) [as .ts] (/Users/kevin/Development/boom-demo/node_modules/ts-node/src/index.ts:406:12)\n    at Module.load (internal/modules/cjs/loader.js:566:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:498:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)\n    at Object.<anonymous> (/Users/kevin/Development/boom-demo/node_modules/ts-node/src/bin.ts:145:12)",
    "message": "hi",
    "isBoom": true,
    "isServer": true,
    "data": null,
    "output": {
        "statusCode": 500,
        "payload": {
            "statusCode": 500,
            "error": "Internal Server Error",
            "message": "An internal server error occurred"
        },
        "headers": {}
    }
}

{
    "isBoom": true,
    "isServer": true,
    "data": null,
    "output": {
        "statusCode": 500,
        "payload": {
            "statusCode": 500,
            "error": "Internal Server Error",
            "message": "An internal server error occurred"
        },
        "headers": {}
    }
}

```

**Comment by 5c077m4n** [comment]
Also, why is the message in the payload not the same as the one on the top level? (not to mention that the boomify() doesn't give a message at all...)

**Comment by thepag** [comment]
The `new Error('message')` is not being passed for the (default) 500 errors.

If you set the options to 400, then the `message` does get carried to the Boom payload message property.
```
Boom.boomify(error, { statusCode: 400 });
```

Setting the code to the default did not work:
```
Boom.boomify(error, { statusCode: 500 });
```
The message was always:
```
"message": "An internal server error occurred"
```

The `message` appeared to be transfered for all `statusCode` I randomly tried, except for the default.

**Comment by thepag** [comment]
I see hiding the 500 error message is intentional. https://github.com/hapijs/boom/blob/master/lib/index.js#L419-L421

```
if (this.output.statusCode === 500) {
  this.output.payload.message = 'An internal server error occurred'; // Hide actual error from user
}
```

Please update the docs. Thank you for sharing.

**Comment by hueniverse** [comment]
First, it is already clearly documented: https://github.com/hapijs/boom#http-5xx-errors
Second, who exactly are you asking to update the docs? Why not just make a PR and contribute?
