### ISSUE TITLE
Use captureStackTrace to remove boom artifacts from stack traces

### ISSUE THREAD

**Issue by kpdecker** [hapijs/boom#67]
Using this https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi the boom stack traces can safely remove their own frames so:

```
Debug: internal, implementation, error
    Error: child "text" fails because ["text" is required]
    at Object.exports.create (/Users/user/project/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/user/project/node_modules/boom/lib/index.js:262:99)
    at Object.exports.badImplementation (/Users/user/project/node_modules/boom/lib/index.js:298:23)
    at postValidate (/Users/user/project/node_modules/hapi/lib/validation.js:194:26)
    at [object Object].internals.Any._validateWithOptions (/Users/user/project/node_modules/joi/lib/any.js:652:16)
    at [object Object].root.validate (/Users/user/project/node_modules/joi/lib/index.js:102:23)
    at exports.response (/Users/user/project/node_modules/hapi/lib/validation.js:213:20)
    at /Users/user/project/node_modules/hapi/lib/request.js:377:13
    at iterate (/Users/user/project/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/user/project/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /Users/user/project/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
```

Could reduce to:

```
Debug: internal, implementation, error
    Error: child "text" fails because ["text" is required]
    at postValidate (/Users/user/project/node_modules/hapi/lib/validation.js:194:26)
    at [object Object].internals.Any._validateWithOptions (/Users/user/project/node_modules/joi/lib/any.js:652:16)
    at [object Object].root.validate (/Users/user/project/node_modules/joi/lib/index.js:102:23)
    at exports.response (/Users/user/project/node_modules/hapi/lib/validation.js:213:20)
    at /Users/user/project/node_modules/hapi/lib/request.js:377:13
    at iterate (/Users/user/project/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/user/project/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /Users/user/project/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
```

Which helps remove noise from throws.

Potential downsides:
- Only works under v8
- Slight bit of additional complexity
- Won't impact `wrap` API (Probably not a downside since it's BYO `Error` object so the user controls the trace already

General pattern is here:
https://github.com/chaijs/chai/blob/4e18d2a49394f21f49eaea97f556d6a17ecbcc7e/chai.js#L5015
https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/exception.js

Glad to do the work to PR this if desired.

**Comment by arb** [comment]
Makes sense to me. I don't think this module needs to care about anything that isn't V8. Will the result look the same if you use `wrap` or does `captureStackTrace` only filter the file(s) where you call from?

My only concern is what are the chances something useful could get filtered out?

**Comment by kanongil** [comment]
I'm doubtful about the usefulness of this. I like being pointed to exactly where the error was created. If you decide to go ahead, please bear in mind that reading the `stack` property is very slow in v8. For instance, I tested the handlebars implementation and it took 10x more time to generate than a plain `Error`.

**Comment by AdriVanHoudt** [comment]
I also like the full one but I can see the use case to remove it, if you do put it behind a flag or something?

**Comment by kpdecker** [comment]
`wrap`: This shouldn't change. If it does, we did it wrong.

Regarding the usefulness, the whole intent of this API is to allow module developers to hide their internals. The only people who should care about the internals of boom are people working on boom and they can hack around that while debugging features. For everyone else showing the first frame as the first location that their code intended to throw vs. something an arbitrary number of frames down is very helpful for quickly debugging failures.

Regarding performance, I'll setup a before after bench suite so we know what the impact may be on that front.

**Comment by AdriVanHoudt** [comment]
`they can hack around that while debugging features` does this imply an option of some sort or...?

**Comment by kpdecker** [comment]
This doesn't have much impact on performance when run in the context of the rest of the boom stack:

```
badRequest x 79,680 ops/sec ±1.93% (84 runs sampled)
trim x 63,649 ops/sec ±1.92% (87 runs sampled)
error x 222,179 ops/sec ±1.56% (89 runs sampled)
capture x 130,351 ops/sec ±1.13% (94 runs sampled)
```

Regarding hack around, I meant that the contributors to this project can comment out the line that has this effect if they are running into problems. The use case is rare enough and this library simple enough that the API overhead is not something that I would pursue but this would be a decision for @arb.
